export class Skills{
   static SKILLS: string[] = [
    "Assembly", "Go", "Rust", "Perl", "R", "Scala", "Groovy", "VBA", "MATLAB", "Julia",
    "COBOL", "Fortran", "Delphi", "Haskell", "Erlang", "JavaScript", "TypeScript", "Angular",
    "React", "Node.js", "Python", "Java", "C++", "C#", "Ruby", "SQL", "NoSQL", "MongoDB",
    "PostgreSQL", "DevOps", "AWS", "Azure", "GCP", "Docker", "Kubernetes", "HTML", "CSS",
    "SCSS", "SASS", "Bootstrap", "TailwindCSS", "Figma", "UI/UX Design", "Photoshop",
    "Illustrator", "PHP", "Laravel", "Spring Boot", "Hibernate", "Express.js", "Django",
    "Flask", "Unity", "Game Development", "Machine Learning", "Deep Learning", "Data Science",
    "Artificial Intelligence", "Blockchain", "Web3", "Cybersecurity", "Penetration Testing",
    "Testing Automation", "Jest", "Cypress", "Selenium", "API Development", "REST", "GraphQL",
    "Mobile Development", "Swift", "Kotlin", "Android", "iOS", "Flutter", "React Native",
    "Xamarin", "Project Management", "Agile", "Scrum", "Kanban", "Git", "GitHub", "GitLab",
    "Bitbucket", "CI/CD", "Terraform", "Ansible", "Chef", "Puppet", "Networking",
    "Virtualization", "Linux", "Unix", "Windows Server", "Salesforce", "SAP", "Tableau",
    "Power BI", "ETL", "Big Data", "Hadoop", "Spark", "Kafka", "Snowflake", "Elasticsearch",
    "Data Engineering", "Cloud Computing", "Microservices", "Event-Driven Architecture",
    "WebAssembly", "jQuery", "D3.js", "Three.js", "EJS", "Handlebars.js", "Next.js", "Nuxt.js",
    "Svelte", "Sapper", "Astro", "Pug", "Mustache", "LitElement", "Polymer", "Ionic",
    "Capacitor", "Apache Cordova", "Corona SDK", "Unreal Engine", "GameMaker Studio",
    "Construct", "NestJS", "Fastify", "Hapi.js", "LoopBack", "Strapi", "Meteor", "Feathers.js",
    "Flask-SocketIO", "Celery", "ASP.NET Core", "Phoenix (Elixir)", "Pyramid", "Tornado",
    "Bottle", "Falcon", "Redis", "Cassandra", "CouchDB", "Neo4j", "Firebase", "Supabase",
    "DynamoDB", "Realm", "CockroachDB", "TimescaleDB", "HBase", "InfluxDB", "Memcached",
    "MariaDB", "VoltDB", "OpenShift", "Rancher", "Packer", "Prometheus", "Grafana", "Zabbix",
    "Splunk", "Jenkins", "Bamboo", "CircleCI", "AWS Lambda", "CloudFormation", "Cloudflare",
    "Heroku", "Netlify", "Vercel", "Ethical Hacking", "Metasploit", "Wireshark", "Nmap",
    "OWASP", "Nessus", "Burp Suite", "Kali Linux", "Fortinet", "Palo Alto",
    "Cyber Threat Intelligence", "Incident Response", "SOC Operations",
    "Vulnerability Assessment", "Risk Management Framework", "TensorFlow", "PyTorch",
    "Scikit-learn", "Keras", "OpenCV", "NLP", "Hugging Face", "Transformers",
    "Reinforcement Learning", "GANs", "YOLO (Object Detection)", "BERT", "GPT Models", "LSTM",
    "Time Series Analysis", "Excel (Advanced)", "Google Sheets", "KNIME", "SAS", "SPSS",
    "Stata", "RapidMiner", "Orange Data Mining", "Data Wrangling", "Data Cleaning",
    "Data Visualization", "Data Mining", "Predictive Analytics", "Statistical Modeling",
    "Sentiment Analysis", "Canva", "Blender", "After Effects", "Premiere Pro", "Sketch",
    "InVision", "Adobe XD", "Axure RP", "Marvel", "Affinity Designer", "Cinema 4D",
    "CorelDRAW", "ZBrush", "Unity UI", "Motion Graphics", "IPv4/IPv6", "BGP", "OSPF", "MPLS",
    "SNMP", "VPN Configuration", "Load Balancing", "Firewalls", "IDS/IPS", "Proxy Servers",
    "Samba", "NFS", "VMware", "Citrix", "Storage Area Networks (SAN)", "Communication",
    "Leadership", "Time Management", "Problem-Solving", "Critical Thinking", "Collaboration",
    "Adaptability", "Emotional Intelligence", "Negotiation", "Conflict Resolution",
    "Public Speaking", "Coaching & Mentoring", "Decision-Making", "Goal Setting", "Creativity",
    "Jira", "Trello", "Asana", "Monday.com", "Notion", "Basecamp", "MS Project",
    "Gantt Charts", "OKRs", "KPIs", "Change Management", "Business Analysis",
    "Product Management", "Roadmapping", "Portfolio Management", "Technical Writing",
    "Grant Writing", "Copywriting", "Content Writing", "SEO Writing", "Blogging",
    "Documentation Tools (Confluence, Wiki)", "Markdown", "White Papers", "Proposal Writing",
    "Editing", "Proofreading", "Style Guides", "APA/MLA Formatting", "Plagiarism Checking",
    "Arduino", "Raspberry Pi", "IoT Development", "Edge Computing", "Robotics",
    "MATLAB Simulink", "PCB Design", "Electrical Circuit Design", "CAD (AutoCAD, SolidWorks)",
    "3D Printing", "Drone Programming", "VR/AR Development", "Unity AR Foundation",
    "Unreal Engine AR", "OpenXR"
  ];

}
