export class StatusKeys{
  
    static ACTIVE=11;
	static INACTIVE=12;
	static HOLD=39;
	static BILLING_PAID=33;
	static BILLING_UNPAID=34;

	static PAY_ACTION_PROCESS=1;
	static PAY_ACTION_HOLD=2;
	static PAYROLL_IN_PROCESS = 55;
	static PAYROLL_PROCESSED = 54;
	static PAYSLIP_FINALIZED = 44;
	static PAYSLIP_DRAFT = 45;

	static ATTENDANCE_UPDATE_REQUEST_PENDING = 52;


	/**
	 * ASSET STATUSES START
	 */
	static ASSET_ASSIGNED = 62;	
	static ASSET_UNAVAILABLE = 63;	
	static ASSET_AVAILABLE = 64;
	static ASSET_MAINTENANCE = 65;
	static ASSET_DAMAGED = 66;
	/**
	 * ASSET STATUSES END
	 */

	/**
	 * RESIGNATION STATUSES START
	 */
	static RESIGNATION_PENDING = 13;	
	/**
	 * RESIGNATION STATUSES END
	 */

}